@token = c7066ac221079352ef6c

POST http://localhost:8080/reservation
Authorization: {{token}}
Content-Type: application/json

{
    "user": "user1",
    "startDate": "startDate",
    "endDate":"endDate",
    "room": "someRoom"
}
###

GET http://localhost:8080/reservation/45cb94d7af76a8a601bf
Authorization: {{token}}
###

GET http://localhost:8080/reservation/all
Authorization: {{token}}
###

PUT http://localhost:8080/reservation/45cb94d7af76a8a601bf
Authorization: {{token}}
Content-Type: application/json

{
    "room": "someOtherRoom",
    "user": "user2"

}
###